#!/usr/bin/env bash
# Wires this vault into your real Claude Desktop config: locates
# claude_desktop_config.json for your OS, backs it up, and merges in the
# filesystem + obsidian-mcp-server entries. Only touches those two keys -
# everything else already in your config is left alone.
#
# Usage: ./scripts/configure-claude-desktop.sh /path/to/vault [--api-key KEY]

set -euo pipefail

VAULT_PATH="${1:?Usage: configure-claude-desktop.sh /path/to/vault [--api-key KEY]}"
shift || true

API_KEY=""
while [ $# -gt 0 ]; do
  case "$1" in
    --api-key) API_KEY="$2"; shift 2 ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MERGE_TOOL="$SCRIPT_DIR/lib/merge-mcp-config.py"
VAULT_PATH_ABS="$(cd "$VAULT_PATH" && pwd)"

case "$(uname -s)" in
  Darwin)
    CONFIG_PATH="$HOME/Library/Application Support/Claude/claude_desktop_config.json" ;;
  Linux)
    # Covers native Linux Claude Desktop builds and WSL. Windows accessed
    # via WSL should instead target the Windows-side path under
    # /mnt/c/Users/<you>/AppData/Roaming/Claude/ - pass that explicitly if
    # this default doesn't match your setup.
    CONFIG_PATH="$HOME/.config/Claude/claude_desktop_config.json" ;;
  MINGW*|MSYS*|CYGWIN*)
    CONFIG_PATH="${APPDATA:?APPDATA not set}/Claude/claude_desktop_config.json" ;;
  *)
    echo "Unrecognized OS ($(uname -s)) - pass the config path manually and adapt this script." >&2
    exit 1 ;;
esac

echo "Claude Desktop config: $CONFIG_PATH"

if [ -f "$CONFIG_PATH" ]; then
  BACKUP="${CONFIG_PATH}.bak-$(date +%Y%m%d%H%M%S)"
  cp "$CONFIG_PATH" "$BACKUP"
  echo "backed up existing config to $BACKUP"
fi

# Best-effort: if no --api-key was given, look for one already generated by
# the Local REST API plugin (only present after Obsidian has run it once).
# Field name isn't guaranteed across plugin versions - this is a
# convenience, not a promise; falls back to a placeholder either way.
if [ -z "$API_KEY" ]; then
  DATA_JSON="$VAULT_PATH_ABS/.obsidian/plugins/obsidian-local-rest-api/data.json"
  if [ -f "$DATA_JSON" ]; then
    FOUND_KEY="$(python3 -c "
import json
try:
    d = json.load(open('$DATA_JSON'))
except Exception:
    d = {}
for k in ('apiKey', 'api_key', 'apiToken'):
    if d.get(k):
        print(d[k])
        break
" 2>/dev/null || true)"
    if [ -n "$FOUND_KEY" ]; then
      API_KEY="$FOUND_KEY"
      echo "found an API key in $DATA_JSON"
    fi
  fi
fi

if [ -z "$API_KEY" ]; then
  API_KEY="paste-your-local-rest-api-key-here"
  echo "no API key given or found — writing a placeholder; edit it in manually"
fi

ENTRIES=$(python3 -c "
import json
print(json.dumps({
    'obsidian-vault': {
        'command': 'npx',
        'args': ['-y', '@modelcontextprotocol/server-filesystem', '$VAULT_PATH_ABS'],
    },
    'obsidian': {
        'command': 'npx',
        'args': ['-y', 'obsidian-mcp-server@latest'],
        'env': {
            'MCP_TRANSPORT_TYPE': 'stdio',
            'OBSIDIAN_API_KEY': '$API_KEY',
            'OBSIDIAN_BASE_URL': 'https://127.0.0.1:27124',
            'OBSIDIAN_VERIFY_SSL': 'false',
        },
    },
}))
")

python3 "$MERGE_TOOL" "$CONFIG_PATH" "$ENTRIES"

echo ""
echo "Done. Restart Claude Desktop (quit fully, not just close the window) to pick this up."
